# Autogenerated header file. Please do not edit. 

# Input structure 
transvarNameList_one_min_subsample_csphotaot_a1 = [
        "aod_cimel_500",
       ]

transvarNameList_one_min_mfrsraod1michc1_c1 = [
        "aod_mfrsr_C1_500",
       ]
transvarNameList_one_min_nimfraod1mich_c1 = [
        "aod_nimfr_500",
       ]
transvarNameList_one_min_mfrsraod1miche13_c1 = [
        "aod_mfrsr_E13_500",
       ]


# Input Offsets 
ONE_MIN_SUBSAMPLE_CSPHOTAOT_A1_AOD_CIMEL_500=0
ONE_MIN_MFRSRAOD1MICHC1_C1_AOD_MFRSR_C1_500=0
ONE_MIN_NIMFRAOD1MICH_C1_AOD_NIMFR_500=0
ONE_MIN_MFRSRAOD1MICHE13_C1_AOD_MFRSR_E13_500=0
