# Autogenerated header file. Please do not edit. 

# Input structure 
invarNameList = [
        "aod_cimel_500",
        "aod_mfrsr_C1_500",
        "aod_mfrsr_E13_500",
        "aod_nimfr_500",
        ]

# Input Offsets 
AOD_CIMEL_500=0
AOD_MFRSR_C1_500=1
AOD_MFRSR_E13_500=2
AOD_NIMFR_500=3
