# Autogenerated header file. Please do not edit. 

# Output structures 
outvarNameList_aodbe_c1 = [
        "base_time",
        "alt",
        "lon",
        "lat",
        "good_data_flag",
        "daily_slope",
        "daily_mean_bias",
        "daily_npoint",
        "daily_RMSD",
        "aod_be_source",
        "aod_be_random_uncertainty",
        "aod_be",
        "aod_mfrsr_C1_500",
        "aod_mfrsr_E13_500",
        "aod_nimfr_500",
        "aod_cimel_500",
        "ncomparisons",
        "time_bounds",
        "time",
        "time_offset",
        ] 

# Output offsets 
AODBE_C1_BASE_TIME = 0
AODBE_C1_ALT = 1
AODBE_C1_LON = 2
AODBE_C1_LAT = 3
AODBE_C1_GOOD_DATA_FLAG = 4
AODBE_C1_DAILY_SLOPE = 5
AODBE_C1_DAILY_MEAN_BIAS = 6
AODBE_C1_DAILY_NPOINT = 7
AODBE_C1_DAILY_RMSD = 8
AODBE_C1_AOD_BE_SOURCE = 9
AODBE_C1_AOD_BE_RANDOM_UNCERTAINTY = 10
AODBE_C1_AOD_BE = 11
AODBE_C1_AOD_MFRSR_C1_500 = 12
AODBE_C1_AOD_MFRSR_E13_500 = 13
AODBE_C1_AOD_NIMFR_500 = 14
AODBE_C1_AOD_CIMEL_500 = 15
AODBE_C1_NCOMPARISONS = 16
AODBE_C1_TIME_BOUNDS = 17
AODBE_C1_TIME = 18
AODBE_C1_TIME_OFFSET = 19
